apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookinfo-productpage
  labels:
    app: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
  template:
    metadata:
      labels:
        app: productpage
    spec:
      containers:
      - name: productpage
        image: ${image}
        ports:
        - containerPort: 8080
  imagePullSecrets:
  - name: demo-k8s-secret
