apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: productpage-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/olegchorny/bookinfo-productpage
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: productpage-image
spec:
  type: image
  params:
    - name: url
      value: docker.io/ochorny/bookinfo-productpage
---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: productpage-pipeline
spec:
  resources:
    - name: source-repo
      type: git
    - name: web-image
      type: image
  tasks:
    - name: build-kaniko
      taskRef:
        name: kaniko
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: image
            resource: web-image
    - name: deploy-web
      taskRef:
        name: deploy-using-kubectl
      resources:
        inputs:
          - name: source
            resource: source-repo
          - name: image
            resource: web-image
            from:
              - build-kaniko
      params:
        - name: path
          value: /workspace/source/ksvc.yaml
        - name: yqArg
          value: "-d0"
        - name: yamlPathToImage
          value: "spec.template.spec.containers[0].image"
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: productpage-pipeline-run-2
spec:
  trigger:
    type: manual
  pipelineRef:
    name: productpage-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: productpage-git
    - name: web-image
      resourceRef:
        name: productpage-image
