name: VKS - build, push and deploy.
on:
  push:
    branches:
    - master
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
#    - uses: azure/container-actions/docker-login@master
#      with:
#        login-server: docker.pkg.github.com/v2
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
   - uses: actions/checkout@master
   - name: Build
     run: |
       sha=${GITHUB_SHA:0:7}
       app="${GITHUB_REPOSITORY#*/}"
       docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha .
   - name: Push
     run: |
       sha=${GITHUB_SHA:0:7}
       app="${GITHUB_REPOSITORY#*/}"
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha
   - name: OpenStack
     run: |
        pip install python-openstackclient
        pip install python-magnumclient
   
#     runs-on: ubuntu-latest
#     steps:
#     - name: Publish to Registry
#       uses: elgohr/Publish-Docker-Github-Action@master
#       with:
#         name: docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
