name: VKS - build, push and deploy.
on:
  push:
    branches:
    - master
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
#    - uses: azure/container-actions/docker-login@master
#      with:
#        login-server: docker.pkg.github.com/v2
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
   - uses: actions/checkout@master
   - name: Build
     run: |
       sha=${GITHUB_SHA:0:7}
       app="${GITHUB_REPOSITORY#*/}"
       docker build -t docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha .
   - name: Push
     run: |
       sha=${GITHUB_SHA:0:7}
       app="${GITHUB_REPOSITORY#*/}"
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$app:$sha
   - name: OpenStack
     run: |
        sudo pip install wheel
        sudo pip install python-openstackclient
        sudo pip install python-magnumclient
        export OS_AUTH_URL=${{ secrets.AUTH_URL }}
        export OS_PROJECT_ID=${{ secrets.PROJECT_ID }}
        export OS_PROJECT_NAME=${{ secrets.PROJECT_NAME }}
        export OS_USER_DOMAIN_NAME=${{ secrets.USER_DOMAIN_NAME }}
        if [ -z "$OS_USER_DOMAIN_NAME" ]; then unset OS_USER_DOMAIN_NAME; fi
        export OS_PROJECT_DOMAIN_ID=${{ secrets.PROJECT_DOMAIN_ID }}
        if [ -z "$OS_PROJECT_DOMAIN_ID" ]; then unset OS_PROJECT_DOMAIN_ID; fi
        unset OS_TENANT_ID
        unset OS_TENANT_NAME
        export OS_USERNAME=${{ secrets.USERNAME }}
        export OS_PASSWORD=${{ secrets.PASSWORD }}
        export OS_REGION_NAME=${{ secrets.REGION_NAME }}
        if [ -z "$OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi
        export OS_INTERFACE=public
        export OS_IDENTITY_API_VERSION=3
        openstack coe cluster list
        export OS_CLUSTER_NAME=${{ secrets.CLUSTER_NAME }}
        cd ~
        openstack coe cluster config knative
#     runs-on: ubuntu-latest
#     steps:
#     - name: Publish to Registry
#       uses: elgohr/Publish-Docker-Github-Action@master
#       with:
#         name: docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
