name: Build and Publish Docker
on: [push]
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
#    - uses: azure/container-actions/docker-login@master
#      with:
#        login-server: docker.pkg.github.com/v2
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
   - uses: actions/checkout@master
   - run: |
       docker login docker.pkg.github.com -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       docker build . -t docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage:latest
       docker push docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage:latest
#     runs-on: ubuntu-latest
#     steps:
#     - name: Publish to Registry
#       uses: elgohr/Publish-Docker-Github-Action@master
#       with:
#         name: docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
