name: Build and Publish Docker
on: [push]
jobs:
  build:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: azure/container-actions/docker-login@master
#      with:
#        login-server: docker.pkg.github.com
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#    - uses: actions/checkout@master
#    - run: |
#        docker build . -t docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage:${{ github.sha }}
#        docker push docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage:${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/olegchorny/bookinfo-productpage/bookinfo-productpage
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
